import './tex'
import './svg/rice-ball'
import './svg/sushi'
import './svg/fish'
import './svg/arrow'
import './svg/chef'
import './machine'
import './floor'

export { texture, boxes } from './tex'
