import './tex'
import './svg/rice-ball'
import './svg/sushi'
import './svg/fish'
import './svg/arrow'
import './svg/chef'
import './wall'
import './machine'

export { texture, boxes } from './tex'
